<a href="https://colab.research.google.com/github/Sanket80/GFG-DS-ML/blob/main/Data_Cleaning_And_Analysis_With_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Dealing with Null Values

### 1. None to np.nan

In [3]:
arr = np.array([1, 2, None, 4, 5,None])
arr

arr[arr == None] = np.nan
arr

array([1, 2, nan, 4, 5, nan], dtype=object)

### 2. Checking the Null Values

In [6]:
arr = np.array([1, 2, np.nan, 4, 5,np.nan])
arr

arr[np.isnan(arr)]

array([nan, nan])

### 3. Removing the Null Values

In [7]:
arr = np.array([1, 2, np.nan, 4, 5,np.nan])
arr

arr[~np.isnan(arr)]

array([1., 2., 4., 5.])

### 4. Filling Null with Fixed Values

In [10]:
arr = np.array([1, 2, np.nan, 4, 5,np.nan])
arr

arr[np.isnan(arr)] = 0
print(arr)

[1. 2. 0. 4. 5. 0.]


### 5. Filling the null with Average

In [12]:
arr = np.array([1, 2, np.nan, 4, 5,np.nan])
arr

arr[np.isnan(arr)] = np.nanmean(arr)
print(arr)

[1. 2. 3. 4. 5. 3.]
