<a href="https://colab.research.google.com/github/Sanket80/GFG-DS-ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Arrays Vs Lists

In [3]:
import numpy as np

### Arrays vs List Comparison

In [ ]:
lst = [1,2,3]
print(lst)

arr = np.array([1,2,3])
print(arr)

print(type(lst))
print(type(arr))
print('--------------------')

print(arr == lst)
print(arr.tolist() == lst)
print("---------------------")

[1, 2, 3]
[1 2 3]
<class 'list'>
<class 'numpy.ndarray'>
--------------------
[ True  True  True]
True
---------------------


### Adding Elements in an Array vs List

In [ ]:
lst = [1,2,3]
arr = np.array([1,2,3])

lst.append(4)
print(lst)

arr = np.append(arr, 4)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


### Removing Elements in an Array vs List

In [ ]:
lst = [1,2,3]
arr = np.array([1,2,3])

lst.pop()
# del lst[-2] , from end
print(lst)

arr = np.delete(arr, -1)    # element from end , -1
print(arr)

[1, 2]
[1 2]


### Updating Elements in an Array vs List

In [ ]:
lst = [1,2,3]
arr = np.array([1,2,3])

lst[1] = 4
print(lst)

arr[1] = 4
print(arr)

[1, 4, 3]
[1 4 3]


### Note: Execution of Arrays is much faster than list

## Converting Data Structures to Arrays

### 1. Converting a tuple to an array

In [ ]:
tup = (1,2,3)
arr = np.array(tup)
print(arr)

[1 2 3]


### 2. Converting a list to an array

In [ ]:
lst = [1,2,3]
arr = np.array(lst)
print(arr)

[1 2 3]


### 3. Converting a Dictionary to an array

In [ ]:
dct = {1: 'apple', 2: 'ball', 3: 'cat'}
arr = np.array(list(dct.items()))
print(arr)

arr_k = np.array(dct.keys())
arr_v = np.array(dct.values())
print(arr_k)
print(arr_v)

[['1' 'apple']
 ['2' 'ball']
 ['3' 'cat']]
dict_keys([1, 2, 3])
dict_values(['apple', 'ball', 'cat'])


### 4. Converting a Set to an array

In [ ]:
st = {1,2,3}
arr = np.array(list(st))
print(arr)

[1 2 3]


### 5. Converting a String to an array

In [ ]:
str1 = 'Hello World'
arr = np.array(list(str))
print(arr)

['H' 'e' 'l' 'l' 'o' ' ' 'W' 'o' 'r' 'l' 'd']


### Conversion to other DataTypes

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

arr_f = arr.astype('float')
print(arr_f)

arr_s = arr.astype('str')
print(arr_s)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
['1' '2' '3' '4' '5']


## Finding details of an Array

### Size of An Array

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.size)

5


### Print shape of an Array

In [ ]:
arr = np.array([1,2])
print(arr.shape)

arr = np.array([[1,2,3], [4,5,6]])  # will print first rows, then the columns
print(arr.shape)

(2,)
(2, 3)


### Print Dimensions of an Array

In [ ]:
arr = np.array([1,2])
print(arr.ndim)

arr = np.array([[1,2,3], [4,5,6]])
print(arr.ndim)

1
2


### Print Data Type of an Array

In [ ]:
print(arr.dtype)

int64


## Copy

### 1. Copy func with Lists

In [ ]:
lst = [1,2,3,4,5]
lst1 = lst
print(lst)
print(lst1)
print('-'*20)

lst[0] = 10
print(lst)
print(lst1)
print('-'*20)

lst1[1] = 20
print(lst)
print(lst1)
# As they both are pointing to the same thing, so changes made will also reflected to another

print('*'*20)
lst = [1,2,3,4,5]
lst2 = lst.copy()
print(lst)
print(lst2)
print('-'*20)

lst[0] = 10
print(lst)
print(lst2)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
--------------------
[10, 2, 3, 4, 5]
[10, 2, 3, 4, 5]
--------------------
[10, 20, 3, 4, 5]
[10, 20, 3, 4, 5]
********************
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
--------------------
[10, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


### 2. Copy Func with Arrays

In [ ]:
# Similar things goes with np Arrays
arr = np.array([1,2,3,4,5])
arr1 = arr
print(arr)
print(arr1)
print('-'*20)

arr[0] = 10
print(arr)
print(arr1)
print('-'*20)

arr1[1] = 20
print(arr)
print(arr1)
print('*'*20)

arr = np.array([1,2,3,4,5])
arr2 = arr.copy()
print(arr)
print(arr2)
print('-'*20)

arr[0] = 10
print(arr)
print(arr2)
print('-'*20)

[1 2 3 4 5]
[1 2 3 4 5]
--------------------
[10  2  3  4  5]
[10  2  3  4  5]
--------------------
[10 20  3  4  5]
[10 20  3  4  5]
********************
[1 2 3 4 5]
[1 2 3 4 5]
--------------------
[10  2  3  4  5]
[1 2 3 4 5]
--------------------


## Creating Fixed Size Arrays

### 1. Zeros

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### 2. Ones

In [ ]:
np.ones((2,3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

### 3.Eye

In [ ]:
np.eye(4)  # Identity Matrix, will have 1 diagonal elements 1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 4. Random Number Generator

In [ ]:
print(np.random.rand(2))
print('-'*20)
print(np.random.rand(2,3))
print('-'*20)
print(np.random.rand(2,3,4))

[0.64435608 0.0295419 ]
--------------------
[[0.22502116 0.8132002  0.81272265]
 [0.38126877 0.10121952 0.71915034]]
--------------------
[[[0.24260891 0.84505375 0.2978488  0.64953427]
  [0.83511369 0.31878936 0.06523171 0.46769768]
  [0.61455763 0.51738386 0.16642548 0.49892547]]

 [[0.25938028 0.6010766  0.33933217 0.18452029]
  [0.04312933 0.00979723 0.86858923 0.40122117]
  [0.21200306 0.64226811 0.57988547 0.51985046]]]


In [ ]:
np.random.randint(1,100,5)

array([ 6, 27, 95, 65, 50])

### 5. Seed

In [ ]:
np.random.seed(10)
np.random.randint(1,100,5)

array([10, 16, 65, 29, 90])

In [ ]:
np.random.seed(10)
np.random.randint(1,100,5)

array([10, 16, 65, 29, 90])

## Range, Arange, linspace, logspace



### 1. range in Lists

In [ ]:
r = range(10)
print(r)

r = range(0,10,2)
print(r)

r = range(10,0,-2)
print(r)

print(6 in r)
print(list(r))

range(0, 10)
range(0, 10, 2)
range(10, 0, -2)
True
[10, 8, 6, 4, 2]


### 2. arange in Numpy

In [ ]:
arr = np.arange(10)
print(arr)

arr = np.arange(0,10,2)
print(arr)

arr = np.arange(10,0,-0.5)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5  1.   0.5]


### 3. linspace

In [ ]:
arr = np.arange(0,10,5)
print(arr)

l = np.linspace(0,10,5)
print(l)
# linspace will create the nos specified with equal dist btw them

l,s = np.linspace(0,10,5, retstep= True)    # will give us the step
print(l)
print(s)

[0 5]
[ 0.   2.5  5.   7.5 10. ]
[ 0.   2.5  5.   7.5 10. ]
2.5


### 4. logspace

In [ ]:
arr = np.logspace(0,10,5)
print(arr)

arr = np.logspace(0,10,5, base=2)
print(arr)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]
[1.00000000e+00 5.65685425e+00 3.20000000e+01 1.81019336e+02
 1.02400000e+03]


## Array Manipulation Essentials: Reshaping, Flattening, Splitting & Merging

### 1. Flattening

In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

arr = arr.flatten()
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


### 2. Reshaping

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

arr = arr.reshape(3,3)
print(arr)
print('-'*20)

arr = np.array([[1,2,3], [4,5,6]])
print(arr)

arr = arr.reshape(3,2)   # actual values and reshapen values must be same
print(arr)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


### 3. Splitting

- vsplit

In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(arr)
print('-'*20)
arr1, arr2 = np.vsplit(arr, 2)
print(arr1)
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------------
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


- hsplit

In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
print('-'*20)
arr1, arr2 = np.hsplit(arr, 2)
print(arr1)
print(arr2)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]


- split

In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
print('-'*20)

arr1, arr2 = np.split(arr, 2, axis=1)  # axis = 0 -> vertical , axis = 1  -> horizontal
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]


### 4. Merging

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 = np.array([9,10,11,12])
print(arr1)
print(arr2)
print('-'*20)

arr = np.concatenate((arr1, arr2, arr3))
print(arr)

[1 2 3 4]
[5 6 7 8]
--------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12]


- hstack

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1)
print(arr2)
print('-'*20)

arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4]
[5 6 7 8]
--------------------
[1 2 3 4 5 6 7 8]


- vstack

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1)
print(arr2)
print('-'*20)

arr = np.vstack((arr1, arr2))
print(arr)

[1 2 3 4]
[5 6 7 8]
--------------------
[[1 2 3 4]
 [5 6 7 8]]


- stack

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1)
print(arr2)
print('-'*20)

arr = np.stack((arr1, arr2), axis=1)
print(arr)


[1 2 3 4]
[5 6 7 8]
--------------------
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


## Broadcasting for Efficient Calculations

### 1. Arithmetic

In [ ]:
a = np.array([1,2,3])
b = np.array([[10,20,30], [40,50,60]])
print(a)
print(b)
print('-'*20)

print(a+5)
print('-'*20)

print(a+b)
print('-'*20)

print(a-b)
print('-'*20)

print(a*b)
print('-'*20)

print(a/b)

[1 2 3]
[[10 20 30]
 [40 50 60]]
--------------------
[6 7 8]
--------------------
[[11 22 33]
 [41 52 63]]
--------------------
[[ -9 -18 -27]
 [-39 -48 -57]]
--------------------
[[ 10  40  90]
 [ 40 100 180]]
--------------------
[[0.1   0.1   0.1  ]
 [0.025 0.04  0.05 ]]


### 2. Comparison

In [ ]:
a = np.array([1,2,3])
b = np.array([[10,20,30], [40,50,60]])
print(a)
print(b)
print('-'*20)

# >
print(a>b)
print('-'*20)

# >=
print(a>=b)
print('-'*20)

# <
print(a<b)
print('-'*20)

# <=
print(a<=b)
print('-'*20)

# ==
print(a==b)
print('-'*20)

# !=
print(a!=b)

[1 2 3]
[[10 20 30]
 [40 50 60]]
--------------------
[[False False False]
 [False False False]]
--------------------
[[False False False]
 [False False False]]
--------------------
[[ True  True  True]
 [ True  True  True]]
--------------------
[[ True  True  True]
 [ True  True  True]]
--------------------
[[False False False]
 [False False False]]
--------------------
[[ True  True  True]
 [ True  True  True]]


### 3. Bitwise

In [ ]:
a = np.array([1,2,3])
b = np.array([[10,20,30], [40,50,60]])
print(a)
print(b)
print('-'*20)

print(np.bitwise_and(a,b))
print('-'*20)

print(np.bitwise_or(a,b))
print('-'*20)

print(np.bitwise_xor(a,b))
print('-'*20)

print(np.bitwise_not(a,b))
print('-'*20)

print(np.left_shift(a,b))
print('-'*20)

print(np.right_shift(a,b))

[1 2 3]
[[10 20 30]
 [40 50 60]]
--------------------
[[0 0 2]
 [0 2 0]]
--------------------
[[11 22 31]
 [41 50 63]]
--------------------
[[11 22 29]
 [41 48 63]]
--------------------
[[-2 -3 -4]
 [-2 -3 -4]]
--------------------
[[0 0 0]
 [0 0 0]]
--------------------
[[0 0 0]
 [0 0 0]]


## Where Clause with Arrays

### 1. 1D Array

In [ ]:
np.random.seed(18)
arr = np.random.randint(1,100,10)
print(arr)
print('-'*20)

print(np.where(arr>50))   # will return indexes
print(arr[np.where(arr>50)])
print('-'*20)

print(np.where(arr>50, 'greater than 50', 'less than 50'))

[43 20 70 63 50 47 67  9 25 99]
--------------------
(array([2, 3, 6, 9]),)
[70 63 67 99]
--------------------
['less than 50' 'less than 50' 'greater than 50' 'greater than 50'
 'less than 50' 'less than 50' 'greater than 50' 'less than 50'
 'less than 50' 'greater than 50']


### 2D Array

In [ ]:
np.random.seed(18)
arr = np.random.randint(1,100,size=(3,3))
print(arr)
print('-'*20)

indices = np.where(arr>50)
print(indices)
print(arr[indices])
print('-'*20)

[[43 20 70]
 [63 50 47]
 [67  9 25]]
--------------------
(array([0, 1, 2]), array([2, 0, 0]))
[70 63 67]
--------------------


## Linear Algebra With Numpy

### 1. Dot Product

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)
print('-'*20)

print(np.dot(a,b))    # Need Same dimension only

[1 2 3]
[4 5 6]
--------------------
32


### 2. Matrix Multiplication

In [7]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

print(np.matmul(A,B))

[[19 22]
 [43 50]]


### 3. Determinant

In [8]:
a = np.array([[1,2], [3,4]])    # + - + for 3X3 Matrix

print(np.linalg.det(a))

-2.0000000000000004


### 4. Transpose

In [9]:
a = np.array([[1,2], [3,4]])

print(np.transpose(a))

[[1 3]
 [2 4]]


### 5. Inverse = A.A^-1 = I

In [10]:
a = np.array([[1,2], [3,4]])

print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


### 6. System of Linear Equations

In [11]:
# 1x1 + 2x2 + 3x3 = 10
# 4x1 + 5x2 + 6x3 = 11
# 7x1 + 8x2 + 10x3 = 12

a = np.array([[1,2,3], [4,5,6], [7,8,10]])
b = np.array([10,11,12])

print(np.linalg.solve(a,b))

[-9.33333333e+00  9.66666667e+00  3.55271368e-15]


### 7. Eigen Values and Eigen Vectors

In [13]:
# Eigen Values -> A-lambda*I, will get lambda values
# Eigen Vectors -> A-lambda*I = 0

a = np.array([[5,4], [1,2]])

print(np.linalg.eig(a))
print('-'*20)

eigen_values, eigen_vectors = np.linalg.eig(a)
print(eigen_values)
print(eigen_vectors)

EigResult(eigenvalues=array([6., 1.]), eigenvectors=array([[ 0.9701425 , -0.70710678],
       [ 0.24253563,  0.70710678]]))
--------------------
[6. 1.]
[[ 0.9701425  -0.70710678]
 [ 0.24253563  0.70710678]]


## Working With Files

### Saving Data in Files

- textfile

In [15]:
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('data.txt', arr)

- npy file

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
np.save('data.npy', arr)

- csv file

In [17]:
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('data.csv', arr, header='a,b,c')

- json

In [19]:
# '{'data' : [1,2,3],[4,5,6]}'

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('data.json', arr, header = '{"data" : [', footer = ']}')

### Reading Data From File

- txtfile

In [20]:
data = np.loadtxt('data.txt')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


- npy file

In [21]:
data = np.load('data.npy')
print(data)

[[1 2 3]
 [4 5 6]]


- csv

In [23]:
data = np.loadtxt('data.csv', skiprows=1)
print(data)

[4. 5. 6.]


- json

In [25]:
data = np.loadtxt('data.json')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


### Writing Data to a File

- Replacing existing content

In [30]:
data = np.array([[1,2,3],[4,5,6]])
np.savetxt('data.txt', data)

data = np.array([11,22,33])
np.savetxt('data.txt', data)

- Appending the data on Existing File

In [ ]:
data = np.array([[1,2,3],[4,5,6]])
np.savetxt('data.txt', data)

data = np.load('data.txt')
print(data)
print('-'*20)
data = np.array([11,22,33])
np.savetxt('data.txt', data, fmt='%d', newline=' ')